# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SewerageDepthEstimator
                                 A QGIS plugin
 Estimate the depth of sewer network based on simplified parameters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-08
        copyright            : (C) 2025 by Leonardo Nazareth
        email                : leonazareth@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SewerageDepthEstimator class from file SewerageDepthEstimator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sewerage_depth_estimator import SewerageDepthEstimator
    return SewerageDepthEstimator(iface)
